[font]
size = 10.0
offset = { x = 1, y = 0}

[font.normal]
family = "SF Mono"
style = "Regular"

[font.bold]
family = "SF Mono"
style = "Bold"

[font.italic]
family = "SF Mono"
style = "Italic"

[font.bold_italic]
family = "SF Mono"
style = "Bold Italic"

[window]
padding = {x = 4, y = 4}

[colors]

[colors.primary]
foreground = "#ffffff"
background = "#202020"

[colors.normal]
    black   = "#000000" # 0 0 0
    red     = "#990000" # 153 0 0
    green   = "#00a600" # 0 166 0
    yellow  = "#999900" # 153 153 0
    blue    = "#0000b2" # 0 0 178
    magenta = "#b200b2" # 178 0 178
    cyan    = "#00a8b8" # 0 168 178
    white   = "#bfbfbf" # 191 191 191
[colors.bright]
    black   = "#666666" # 102 102 102
    red     = "#E60000" # 230 0 0
    green   = "#00D900" # 0 217 0
    yellow  = "#E6E600" # 230 230 0
    blue    = "#0000FF" # 0 0 255
    magenta = "#E600E6" # 230 0 230
    cyan    = "#00E6E6" # 0 230 230
    white   = "#E6E6E6" # 230 230 230
