[font]
size = 10.0
offset = { x = 1, y = 0}

[font.normal]
family = "SF Mono"
style = "Regular"

[font.bold]
family = "SF Mono"
style = "Bold"

[font.italic]
family = "SF Mono"
style = "Italic"

[font.bold_italic]
family = "SF Mono"
style = "Bold Italic"

# [env] # doesn't seem to do anything
# term = "xterm-256color"

[colors]

[colors.primary]
foreground = "#ffffff"
background = "#202020"

[window]
padding = {x = 4, y = 4}
