#import = ["/home/matt/.config/alacritty/snazzy.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 8
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }

#normal = { family = "Fixedsys Excelsior", style = "Regular" }
#bold = { family = "Fixedsys Excelsior", style = "Regular" }

#normal = { family = "Source Code Pro", style = "Regular" }
#bold = { family = "Source Code Pro", style = "Bold" }
#normal = { family = "DejaVu Sans Mono", style = "Regular" }

#offset = {x = 1, y = 0}

[window]
title = "alacritty"

[window.dimensions]
columns = 100
lines = 35

[window.position]
x = 150
y = 100
