#!/bin/bash

##########################################
# NapSystem                              #
# Baseline debian server configuration   #
# for my software development needs      #
# (c) Matt Nappo                         #
##########################################

# install sudo
su -c 'apt-get install sudo'

# update system
sudo apt-get update -y
sudo apt-get upgrade -y

# install packages
sudo apt-get install -y git tmux zsh neovim gcc g++ make cmake python3 python3-pip python3-dev build-essential libssl-dev wget curl llvm libtool autoconf automake gdb valgrind clang llvm-dev linux-headers-$(uname -r)

# install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# install docker
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh

# install oh my zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# install dotfiles
bash install.sh

